version: '2'
volumes:
    config:
services:
  homeassistant:
    image: homeassistant/home-assistant:stable
    ports:
      - 80:8123
    privileged: true
    volumes:
      - 'config:/config'
    restart: always
  hass-configurator:
    image: causticlab/hass-configurator-docker:x86_64
    restart: always
    ports:
      - "8080:3218"
    volumes:
      - 'config:/hass-config'
