homeassistant:
  name: Home
  unit_system: metric
  time_zone: Europe/Copenhagen
  external_url: !env_var HOMEASSISTANT_EXTERNAL_URL 

lovelace:
  mode: yaml

# group: !include groups.yaml
# automation: !include automations.yaml
# script: !include scripts.yaml
# scene: !include scenes.yaml

# Text to speech
tts:
  - platform: google_translate
      
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

mqtt:  
  broker: mqtt
  
cast:
  media_player:
    - host: 192.168.86.172

sonos:
  media_player:
    hosts:
      - 192.168.86.172

spotify:
  client_id: !env_var SPOTIFY_ID 
  client_secret: !env_var SPOTIFY_TOKEN

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
  - platform: pocketcasts
    username: !env_var POCKET_CASTS_USER
    password: !env_var POCKET_CASTS_PASSWORD
  - platform: google_wifi
    host: 192.168.86.1
  - platform: worldclock
    time_zone: US/Central 
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.humidity }}"
    name: "sense_humidity"
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.temperature }}"
    name: "sense_temperature_c"
    unit_of_measurement: "degrees"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ ((float(value_json.fields.temperature) * 9 / 5) + 32) | round(1) }}"
    name: "sense_temperature_f"
    unit_of_measurement: "degrees"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.air_quality_score }}"
    name: "sense_air_quality_score"
    unit_of_measurement: "score"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.pressure }}"
    name: "sense_pressure"
    unit_of_measurement: "mbar"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.air_quality_score_accuracy }}"
    name: "sense_air_quality_score_accuracy"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.bvoce_ppm }}"
    name: "sense_bvoce_ppm"
    unit_of_measurement: "ppm"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.eco2_ppm }}"
    name: "sense_eco2_ppm"
    unit_of_measurement: "ppm"
