
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://930b7750f89431869afc2f01d97622eb.balena-devices.com

# Text to speech
tts:
  - platform: google_translate

sensor:
  - platform: google_wifi
    host: 192.168.86.1
  - platform: worldclock
    time_zone: !env_var TZ
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - windDirection
      - humidity
      - fog
      - cloudiness
      
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

# TODO: Switch to lovelace: https://github.com/dnguyen800/spotify-playlist-card
spotify:
  client_id: a8f7a5cafb284c3da398873c47fff910
  client_secret: !env_var SPOTIFY_TOKEN

mqtt:  
  broker: mqtt
  
calendar:
  - platform: todoist
    token: !env_var TODOIST_TOKEN
    custom_projects:
      - name: 'Byggetilladelse'
      - name: 'Home'
        due_date_days: 7
      - name: 'Due Today'
        due_date_days: 0
      - name: 'Due This Week'
        due_date_days: 7
        
cast:
  media_player:
    - host: 192.168.86.26
    - host: 192.168.86.162
    
homeassistant:
  customize:
    input_boolean.stuen_audio_state:
      hidden: true
    media_player.stuen_audio:
      hidden: true
    media_player.stuen_audio:
      friendly_name: Stuen Audio

input_boolean:
  stuen_audio_state:

media_player:
- platform: universal
  name: Stuen Audio Player
  state_template: >
    {% if is_state('media_player.stuen_audio', 'idle') and is_state('input_boolean.stuen_audio_state', 'off') %}
    off
    {% else %}
    {{ states('media_player.stuen_audio') }}
    {% endif %}
  children:
    - media_player.stuen_audio
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.stuen_audio
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.stuen_audio
    volume_up:
      service: switch.turn_on
      data:
        entity_id: switch.stuen_audio
    volume_down:
      service: switch.turn_on
      data:
        entity_id: switch.stuen_audio
    volume_mute:
      service: switch.turn_on
      data:
        entity_id: switch.stuen_audio
    play_discover_weekly:
      service: media_player.play_media
      data_template:
        entity_id: media_player.stuen_audio
        media_content_id: https://open.spotify.com/playlist/37i9dQZEVXcSERsyBdeqKD?si=KRMjs62JTAmpGmvL-nFXqg
        media_content_type: playlist
  attributes:
    state: switch.stuen_audio
    is_volume_muted: media_player.stuen_audio|is_volume_muted
    volume_level: media_player.stuen_audio|volume_level
    source: media_player.stuen_audio|source
    source_list: media_player.stuen_audio|source_list

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# sensors
# balenaSense sensors added by script
sensor:
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.humidity }}"
    name: "sense_humidity"
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.temperature }}"
    name: "sense_temperature_c"
    unit_of_measurement: "degrees"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ ((float(value_json.fields.temperature) * 9 / 5) + 32) | round(1) }}"
    name: "sense_temperature_f"
    unit_of_measurement: "degrees"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.air_quality_score }}"
    name: "sense_air_quality_score"
    unit_of_measurement: "score"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.pressure }}"
    name: "sense_pressure"
    unit_of_measurement: "mbar"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.air_quality_score_accuracy }}"
    name: "sense_air_quality_score_accuracy"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.bvoce_ppm }}"
    name: "sense_bvoce_ppm"
    unit_of_measurement: "ppm"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.eco2_ppm }}"
    name: "sense_eco2_ppm"
    unit_of_measurement: "ppm"
    
frontend:
  themes:
    dark:
      # Background image
      lovelace-background: 'center / cover no-repeat url("/local/night.jpg") fixed'
    
      # Colors
      text-color: '#DADADB'                                                           # Grey text
      text-medium-light-color: '#A0A2A8'                                              # Medium-light grey text
      text-medium-color: '#80828A'                                                    # Medium grey text
      text-dark-color: '#6A6B74'                                                      # Dark grey text
      accent-color: '#008bef'                                                         # Blue
      accent-medium-color: '#2686c1'                                                  # Decent blue
      background-color: '#3b4049'                                                     # Dark grey background
      background-color-2: '#484E59'                                                   # Light grey background
      background-card-color: '#434952'                                                # Grey background
      border-color: '#383C46'                                                         # Grey border
    
      # Header
      app-header-background-color: '#363941'                                          # Background color
      
      # Text
      primary-color: 'var(--text-color)'
      text-primary-color: 'var(--text-color)'
      
      # Left Menu
      paper-listbox-background-color: 'var(--background-color)'                       # Background
      sidebar-icon-color: 'var(--text-medium-color)'                                  # icons
      sidebar-selected-icon-color: 'var(--text-medium-light-color)'                   # Selected row icon and background (15%)
      sidebar-selected-text-color: 'var(--text-color)'                                # Selected row label
    
      # UI
      paper-card-header-color: 'var(--text-color)'                                    # Title in settings
      primary-background-color: 'var(--background-color)'                             # Background (also title background in left menu)
      mdc-theme-primary: 'var(--accent-medium-color)'                                 # Action Buttons (save, restart etc.)
      card-background-color: 'var(--background-card-color)'                           # Entity Registry Background
      
      # Card
      paper-card-background-color: 'var(--background-card-color)'                     # Background
      dark-primary-color: 'var(--text-color)'
      primary-text-color: 'var(--text-color)'
      paper-listbox-color: 'var(--text-color)'
      light-primary-color: 'var(--text-dark-color)'
      secondary-text-color: 'var(--text-medium-color)'
      disabled-text-color: 'var(--text-dark-color)'
      paper-dialog-button-color: 'var(--text-color)'
      secondary-background-color: 'var(--background-color-2)'                         # Background more info title
    
      # Icons
      paper-item-icon-color: 'var(--text-dark-color)'                                 # Off
      paper-item-icon-active-color: 'var(--accent-color)'                             # On
      
      # Switches
      switch-checked-button-color: 'var(--text-medium-light-color)'                   # Knob On
      switch-unchecked-button-color: 'var(--text-medium-light-color)'                 # Knob Off
      switch-checked-track-color: '#009FFF'                                           # Background On
      switch-unchecked-track-color: '#767682'                                         # Background Off
    
      # Slider
      paper-slider-active-color: 'var(--accent-color)'                                # Line On
      paper-slider-container-color: 'var(--text-dark-color)'                          # Line Off
      paper-slider-knob-color: 'var(--text-medium-light-color)'                       # Knob On
      paper-slider-knob-start-color: 'var(--text-medium-light-color)'                 # Knob Off
      
      # Shadows
      ha-card-box-shadow: 'inset 0px 0px 0px 1px var(--border-color)'
