# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !env_var BASE_URL 
  
frontend:
  javascript_version: latest
  themes: !include ./themes
 
# Text to speech
tts:
  - platform: google_translate
      
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - ping
    - download
    - upload

# TODO: Switch to lovelace: https://github.com/dnguyen800/spotify-playlist-card
spotify:
  client_id: !env_var SPOTIFY_ID 
  client_secret: !env_var SPOTIFY_TOKEN

mqtt:  
  broker: mqtt
  
calendar:
  - platform: todoist
    token: !env_var TODOIST_TOKEN
    custom_projects:
      - name: 'Byggetilladelse'
      - name: 'Home'
        due_date_days: 7
      - name: 'Due Today'
        due_date_days: 0
      - name: 'Due This Week'
        due_date_days: 7
        
cast:
  media_player:
    - host: 192.168.86.26
    - host: 192.168.86.162
    
homeassistant:
  customize:
    input_boolean.stuen_audio_state:
      hidden: true
    media_player.stuen_audio:
      hidden: true
    media_player.stuen_audio:
      friendly_name: Stuen Audio

input_boolean:
  stuen_audio_state:

media_player:
- platform: universal
  name: Stuen Audio Player
  state_template: >
    {% if is_state('media_player.stuen_audio', 'idle') and is_state('input_boolean.stuen_audio_state', 'off') %}
    off
    {% else %}
    {{ states('media_player.stuen_audio') }}
    {% endif %}
  children:
    - media_player.stuen_audio
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.stuen_audio
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.stuen_audio
    volume_up:
      service: switch.turn_on
      data:
        entity_id: switch.stuen_audio
    volume_down:
      service: switch.turn_on
      data:
        entity_id: switch.stuen_audio
    volume_mute:
      service: switch.turn_on
      data:
        entity_id: switch.stuen_audio
    play_discover_weekly:
      service: media_player.play_media
      data_template:
        entity_id: media_player.stuen_audio
        media_content_id: https://open.spotify.com/playlist/37i9dQZEVXcSERsyBdeqKD?si=KRMjs62JTAmpGmvL-nFXqg
        media_content_type: playlist
  attributes:
    state: switch.stuen_audio
    is_volume_muted: media_player.stuen_audio|is_volume_muted
    volume_level: media_player.stuen_audio|volume_level
    source: media_player.stuen_audio|source
    source_list: media_player.stuen_audio|source_list

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: pocketcasts
    username: POCKET_CASTS_USER
    password: POCKET_CASTS_PASSWORD
  - platform: google_wifi
    host: 192.168.86.1
  - platform: worldclock
    time_zone: Europe/Copenhagen 
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - windDirection
      - humidity
      - fog
      - cloudiness
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.humidity }}"
    name: "sense_humidity"
    unit_of_measurement: "%"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.temperature }}"
    name: "sense_temperature_c"
    unit_of_measurement: "degrees"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ ((float(value_json.fields.temperature) * 9 / 5) + 32) | round(1) }}"
    name: "sense_temperature_f"
    unit_of_measurement: "degrees"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.air_quality_score }}"
    name: "sense_air_quality_score"
    unit_of_measurement: "score"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.pressure }}"
    name: "sense_pressure"
    unit_of_measurement: "mbar"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.air_quality_score_accuracy }}"
    name: "sense_air_quality_score_accuracy"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.bvoce_ppm }}"
    name: "sense_bvoce_ppm"
    unit_of_measurement: "ppm"
  - platform: mqtt
    state_topic: "balena-sense/+/balena-sense"
    value_template: "{{ value_json.fields.eco2_ppm }}"
    name: "sense_eco2_ppm"
    unit_of_measurement: "ppm"
